### ISSUE TITLE
Potential corner case when signing message and registering key

### ISSUE THREAD

**Issue by sideround** [cyberconnecthq/cyberconnect-swift-lib#1]
**Description**
using the P256 keys stored in the keychain after deleting the app returns an invalid signature when trying to connect/disconnect an address

**To reproduce**
- Authorize wallet using walletconnect
- Generate a pair of P256 keys (for the first time) and store them in the keychain
- Sign the message to get the signature
- Register the signature to CyberConnect - works this time
- Delete the app
- Authorize wallet again
- Retrieve the pair of keys stored in the keychain, sign the message again, and register the signature back to CyberConnect (internal server error)

Potential solution 
- Every time user tries to sign in, a new pair of P256 keys is generated
- Knowing beforehand if keys stored in the keychain are valid

**Comment by Santiago0412** [comment]
1786196df435bccbfdbc646ecbee85194e82d80d
